/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.simple_logbook;

/*
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'simple_logbook.greeting' plugin.
 */

/*
public class Simple_logbookPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("simple_logbook.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}


 */
