package alertsystem;

import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.sql.DataSource;
import java.util.Properties;

public class EmailSender
{
    /*public static void main(String[] args) throws Exception {
        sendMail("krithika.balaji18@gmail.com"); //Note: sender and recipient is the same
    }*/

    public static void sendMail(String recipient, String recipient_name) throws Exception {
        System.out.println("Preparing to send email...");
        Properties properties = new Properties(); //used to configure the properties of the mail - it's a key-value store

        //In order to send a mail using your application - need to configure minimum 4 fields
        properties.put("mail.smtp.auth", "true"); //defines whether an authentication is required for the email server - for gmail it is mandatory to have a username and password
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");

        String myAccountEmail = "krithika.balaji18@gmail.com";
        String password = "!gr@du@t3d!!";

        Session session = Session.getInstance(properties, new Authenticator(){
            @Override
            protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication(myAccountEmail, password);
            }
        });

        Message message = prepareMessage(session, myAccountEmail, recipient, recipient_name);
        System.out.println("I am entering the Transport.send(message) section...");

        Transport.send(message);

        System.out.println("Message sent successfully!");
    }

    private static Message prepareMessage(Session session, String myAccountEmail, String recipient, String recipient_name)
    {
        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(myAccountEmail));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(recipient));

            String subjectString = "registrationFX.src.sample.Patient "+recipient_name + " needs your attention.";
            message.setSubject(subjectString);

            //Create the message part
            BodyPart messageBodyPart = new MimeBodyPart();

            //Now set the actual message
            String messageString = "Hello,\n\n" + recipient_name + "'s Blood Glucose Levels are beyond the advisory levels and requires your attention. Please find attached the document containing your patient's information.\n\nThis message has been autogenerated by DBAle so please don't reply to this email.\n\nRegards,\nDBAle";
            messageBodyPart.setText(messageString);

            //Create a multipart message
            Multipart multipart = new MimeMultipart();

            //Set text message part
            multipart.addBodyPart(messageBodyPart);

            //Working on the attachment
            messageBodyPart = new MimeBodyPart();
            String filename = "C:/PRG3/SendEmailV2/src/main/java/lectureDBP.pdf";
            FileDataSource source = new FileDataSource(filename);
            messageBodyPart.setDataHandler(new DataHandler(source));
            messageBodyPart.setFileName(filename);
            multipart.addBodyPart(messageBodyPart);

            //send the completed message parts
            message.setContent(multipart);
            return message;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
}